# https://docs.docker.com/compose/
version: "3.9"
services:
  rabbitmq:
    container_name: rabbitmq-practice
    build: ./rabbitmq
    ports:
      - "15672:15672"
      - "1883:1883"
    volumes:
      - ./rabbitmq/config/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf